In [2]:
import numpy as np
np.random.seed()
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
w0 = 2 * np.random.random((3,4)) - 1
w1 = 2 * np.random.random((4,1)) - 1
for i in range(500):
    l1 = np.tanh(np.dot(X,w0))
    #l1 = 1/(1+np.exp(-(np.dot(X,w0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,w1))))
    dl2 = (y - l2) * (l2 * (1 - l2))
    dl1 = dl2.dot(w1.T) * (1 - l1 ** 2)
    #dl1 = dl2.dot(w1.T) * (11 * (1-l1))
    w1 += np.dot(l1.T, dl2)
    w0 += np.dot(X.T, dl1)
    print(l2.T) if i % 100 == 0 else None
    #if np.sum(np.square(y - l2)) < 0.01:
    #    print(i, l2.T)
    #    break

[[0.35975646 0.42176856 0.43519308 0.4929719 ]]
[[0.05390016 0.8886506  0.88315011 0.13035974]]
[[0.02521896 0.94104929 0.93964209 0.06778156]]
[[0.01791558 0.95598748 0.9551425  0.05049989]]
[[0.01438223 0.96356079 0.96294097 0.04178179]]
